import 'package:provider/provider.dart';
import 'package:flutter/material.dart';
import '../Provider/app_provider.dart';

String t(BuildContext context, String key) {
  final lang = context.watch<AppProvider>().currentLanguage;
  return LanguageStrings.languages[lang]?[key] ?? key;
}


class LanguageStrings {
  static Map<String, Map<String, String>> languages = {
    'en': {
      // General
      'survey_Stats': 'Survey Stats',
      'survey_overview': 'Survey Overview',
      'pending_survey': 'Pending Survey',
      'total_surveys': 'Total Surveys',
      'view_all': 'View All',
      'completed': 'Completed',
      'approved_land': 'Approved Land',
      'pending': 'Pending',
      'consent_forms': 'Consent Forms',
      'survey_id': 'Survey ID',
      'land_village_district': 'Land village, District',
      'land_area': 'Land Area (in acres)',
      'substation_name': 'Sub-station Name',
      'land_type': 'Land Type',
      'commercial': 'Commercial',
      'capacity': 'Capacity',
      'upload_consent': 'Upload Consent',
      'edit': 'Edit',
      'delete': 'Delete',
      "syncNow": "Sync Now",
      'survey': 'Survey',
      'home': 'Home',
      'consent': 'Consent',
      'dashboard': 'Dashboard',
      'survey_listing': 'Survey Listing',
      'search': 'Search',
      'consent_listing': 'Consent Listing',
      'approved_survey': 'Approved Survey',
      'rejected_survey': 'Rejected Survey',
      'confirm_location': 'Confirm Location',
      'select_location_method': 'How would you like to select your location ?',
      'select_substaion_location_method':
          'How would you like to select your Substation location ?',
      'add_manually': 'Add Manually',
      'select_location': 'Select Location',
      'land_details': 'Land Details',
      'add_survey': 'Add Survey',

      // Land & Substation Details
      'sub_basic_detail': 'Land Details',
      'other_detail': 'Other Details',
      'substation_detail': 'Substation Details',
      'solar_park_ac_capacity':
          'Solar Park AC Capacity (MW)/ DC Capacity (MWp)',
      'solar_park_ac_capacity_hint': 'Enter solar park AC Capacity',
      'grid_connectivity': 'Grid connectivity S/S for inter connection',
      'grid_connectivity_hint': 'Enter Grid connectivity',
      'land_state': 'Land Location, DHQ, State',
      'land_state_hint': 'Enter Land Location, DHQ, State',
      'land_district': 'Land District',
      'land_district_hint': 'Enter Land District',
      'land_taluka': 'Land Taluka',
      'land_taluka_hint': 'Enter Land Taluka',
      'land_village': 'Land Village',
      'land_village_hint': 'Enter Land Village',
      'land_lat': 'Land Latitude',
      'land_lat_hint': 'Enter Land Latitude',
      'land_long': 'Land Longitude',
      'land_long_hint': 'Enter Land Longitude',
      'land_area_val': 'Land Area',
      'land_area_hint': 'Enter Land Area',
      'land_type_val': 'Land Type',
      'land_type_hint': 'Select Land Type',
      'land_rate': 'Land Rate/Commercial/Escalation',
      'land_rate_hint': 'Enter Land Rate/Commercial/Escalation',
      'substation_name_val': 'Sub-station Name',
      'substation_name_hint': 'Enter Sub-station Name',
      'substation_district': 'Sub-station District',
      'substation_district_hint': 'Select Sub-station District',
      'substation_taluka': 'Sub-station Taluka',
      'substation_taluka_hint': 'Select Sub-station Taluka',
      'substation_village': 'Sub-station Village',
      'substation_village_hint': 'Select Sub-station Village',
      'substation_lat': 'Sub-station Latitude',
      'substation_lat_hint': 'Enter Sub-station Latitude',
      'substation_long': 'Sub-station Longitude',
      'substation_long_hint': 'Enter Sub-station Longitude',
      'substation_incharge_name': 'Sub-station Incharge Name',
      'substation_incharge_name_hint': 'Enter Sub-station Incharge Name',
      'substation_incharge_contact': 'Sub-station Incharge Contact',
      'substation_incharge_contact_hint': 'Enter Sub-station Incharge Contact',
      'operator_name': 'Operator Name',
      'operator_name_hint': 'Enter Operator Name',
      'operator_contact': 'Operator Contact',
      'operator_contact_hint': 'Enter Operator Contact',
      'substation_voltage_level': 'Sub-station voltage level',
      'substation_voltage_level_hint': 'Enter Sub-station voltage level',
      'substation_capacity': 'Sub-station Capacity',
      'substation_capacity_hint': 'Enter Sub-station capacity',
      'distance': 'Distance between Sub-station to land',
      'distance_hint': 'Enter Distance between Sub-station to land',
      'plot_distance': 'Plot Distance from Main Road',
      'plot_distance_hint': 'Enter Plot Distance from Main Road',
      'evacuation': 'Evacuation Level',
      'evacuation_hint': 'Enter Evacuation Level',
      'type_of_soil': 'Type of Soil/ Land Profile Terrain',
      'type_of_soil_hint': 'Enter Type of Soil/ Land Profile Terrain',
      'wind_zone': 'Wind Zone',
      'wind_zone_hint': 'Enter Wind Zone',
      'ground_water_rainfall_type': 'Ground Water/Rain Fall',
      'nearest_highway': 'Nearest Highway',
      'nearest_highway_hint': 'Enter Nearest Highway',
      "land_form_image": "Land Form Image",
      'land_images': 'Land Images',
      'save_exit': 'Save & Exit',
      'previous': 'Previous',
      'submit': 'Submit',
      'continue': 'Continue',

      'are_you_sure_logout': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'logout': 'Logout',
      'rejected': 'Rejected',
      'approved': 'Approved',
      'add_consent': 'Add Consent',
      'select_district': 'Select District',
      'select_taluka': 'Select Taluka',
      'select_village': 'Select Village',

      "add_land_Survey": "Add Land Survey",
      "select_survey_no": "Select Survey No",
      "survey_no": "Survey No",
      "search_survey_no_hint": "Search by survey no,lat,long,area",
      "add_file": "Add File",
      "file": "File",
      "upload_consent_forn": "Upload Consent Form"
    },
    'hi': {
      // General
      'survey_overview': 'सर्वेक्षण अवलोकन',
      'pending_survey': 'लंबित सर्वेक्षण',
      'total_surveys': 'कुल सर्वेक्षण',
      'view_all': 'सभी देखें',
      'completed': 'पूर्ण',
      'pending': 'लंबित',
      'consent_forms': 'स्वीकृति प्रपत्र',
      'survey_id': 'सर्वेक्षण आईडी',
      'land_village_district': 'भूमि गाँव, जिला',
      'land_area': 'भूमि क्षेत्र (एकड़ में)',
      'substation_name': 'उप-स्टेशन का नाम',
      'land_type': 'भूमि प्रकार',
      'commercial': 'वाणिज्यिक',
      'capacity': 'क्षमता',
      'upload_consent': 'स्वीकृति अपलोड करें',
      'edit': 'संपादित करें',
      'delete': 'हटाएँ',
      'survey': 'सर्वेक्षण',
      'home': 'मुखपृष्ठ',
      'consent': 'स्वीकृति',
      'dashboard': 'डैशबोर्ड',
      'survey_listing': 'सर्वेक्षण सूची',
      'search': 'खोज',
      'consent_listing': 'स्वीकृति सूची',
      'approved_survey': 'स्वीकृत सर्वेक्षण',
      'rejected_survey': 'अस्वीकृत सर्वेक्षण',
      'confirm_location': 'स्थान की पुष्टि करें',
      'select_location_method': 'आप अपना स्थान कैसे चुनना चाहेंगे?',
      "select_substaion_location_method":
          "आप सबस्टेशन का स्थान कैसे चुनना चाहेंगे?",
      'add_manually': 'मैन्युअली जोड़ें',
      'select_location': 'स्थान चुनें',
      'land_details': 'भूमि विवरण',
      'add_survey': 'सर्वेक्षण जोड़ें',

      // Land & Substation Details
      'sub_basic_detail': 'भूमि विवरण',
      'other_detail': 'अन्य विवरण',
      'substation_detail': 'सबस्टेशन विवरण',
      'solar_park_ac_capacity': 'सोलर पार्क एसी क्षमता (MW)/ DC क्षमता (MWp)',
      'solar_park_ac_capacity_hint': 'सोलर पार्क एसी क्षमता दर्ज करें',
      'grid_connectivity': 'इंटर कनेक्शन के लिए ग्रिड कनेक्टिविटी S/S',
      'grid_connectivity_hint': 'ग्रिड कनेक्टिविटी दर्ज करें',
      'land_state': 'भूमि स्थान, DHQ, राज्य',
      'land_state_hint': 'भूमि स्थान, DHQ, राज्य दर्ज करें',
      'land_district': 'भूमि जिला',
      'land_district_hint': 'भूमि जिला दर्ज करें',
      'land_taluka': 'भूमि तालुका',
      'land_taluka_hint': 'भूमि तालुका दर्ज करें',
      'land_village': 'भूमि गाँव',
      'land_village_hint': 'भूमि गाँव दर्ज करें',
      'land_lat': 'भूमि अक्षांश',
      'land_lat_hint': 'भूमि अक्षांश दर्ज करें',
      'land_long': 'भूमि देशांतर',
      'land_long_hint': 'भूमि देशांतर दर्ज करें',
      'land_area_val': 'भूमि क्षेत्र',
      'land_area_hint': 'भूमि क्षेत्र दर्ज करें',
      'land_type_val': 'भूमि प्रकार',
      'land_type_hint': 'भूमि प्रकार चुनें',
      'land_rate': 'भूमि दर/व्यावसायिक/वृद्धि',
      'land_rate_hint': 'भूमि दर/व्यावसायिक/वृद्धि दर्ज करें',
      'substation_name_val': 'उप-स्टेशन नाम',
      'substation_name_hint': 'उप-स्टेशन नाम दर्ज करें',
      'substation_district': 'उप-स्टेशन जिला',
      'substation_district_hint': 'उप-स्टेशन का जिला चुनें',

      'substation_taluka': 'उप-स्टेशन तालुका',
      'substation_taluka_hint': 'उप-स्टेशन का तालुका चुनें',

      'substation_village': 'उप-स्टेशन गाँव',
      'substation_village_hint': 'उप-स्टेशन का गाँव चुनें',

      'substation_lat': 'उप-स्टेशन अक्षांश',
      'substation_lat_hint': 'उप-स्टेशन अक्षांश दर्ज करें',
      'substation_long': 'उप-स्टेशन देशांतर',
      'substation_long_hint': 'उप-स्टेशन देशांतर दर्ज करें',
      'substation_incharge_name': 'उप-स्टेशन प्रभारी नाम',
      'substation_incharge_name_hint': 'उप-स्टेशन प्रभारी नाम दर्ज करें',
      'substation_incharge_contact': 'उप-स्टेशन प्रभारी संपर्क',
      'substation_incharge_contact_hint': 'उप-स्टेशन प्रभारी संपर्क दर्ज करें',
      'operator_name': 'ऑपरेटर नाम',
      'operator_name_hint': 'ऑपरेटर नाम दर्ज करें',
      'operator_contact': 'ऑपरेटर संपर्क',
      'operator_contact_hint': 'ऑपरेटर संपर्क दर्ज करें',
      'substation_voltage_level': 'उप-स्टेशन वोल्टेज स्तर',
      'substation_voltage_level_hint': 'उप-स्टेशन वोल्टेज स्तर दर्ज करें',
      'substation_capacity': 'उप-स्टेशन क्षमता',
      'substation_capacity_hint': 'उप-स्टेशन क्षमता दर्ज करें',
      'distance': 'भूमि से उप-स्टेशन की दूरी',
      'distance_hint': 'भूमि से उप-स्टेशन की दूरी दर्ज करें',
      'plot_distance': 'मुख्य सड़क से प्लॉट की दूरी',
      'plot_distance_hint': 'मुख्य सड़क से प्लॉट की दूरी दर्ज करें',
      'evacuation': 'एवाक्यूएशन स्तर',
      'evacuation_hint': 'एवाक्यूएशन स्तर दर्ज करें',
      'type_of_soil': 'मिट्टी/भूमि प्रोफ़ाइल प्रकार',
      'type_of_soil_hint': 'मिट्टी/भूमि प्रोफ़ाइल प्रकार दर्ज करें',
      'wind_zone': 'विंड ज़ोन',
      'wind_zone_hint': 'विंड ज़ोन दर्ज करें',
      'ground_water_rainfall_type': 'भूजल/वर्षा',
      'nearest_highway': 'निकटतम हाईवे',
      'nearest_highway_hint': 'निकटतम हाईवे दर्ज करें',
      'land_form_image': 'भूमि फॉर्म छवि',
      'land_images': 'भूमि छवियां',
      'save_exit': 'सहेजें और बाहर निकलें',
      'previous': 'पिछला',
      'submit': 'सबमिट करें',
      'continue': 'जारी रखें',

      'are_you_sure_logout': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'logout': 'लॉगआउट',
      'rejected': 'अस्वीकृत',
      'approved_land': 'स्वीकृत भूमि',
      'survey_Stats': 'सर्वेक्षण आंकड़े',
      'approved': 'स्वीकृत',
      'add_consent': 'अनुमति जोड़ें',
      'select_district': 'जिला चुनें',
      'select_taluka': 'तालुका चुनें',
      'select_village': 'गाँव चुनें',
      'syncNow': 'अब सिंक करें',

      "add_land_Survey": "भूमि सर्वे जोड़ें",
      "select_survey_no": "सर्वे नंबर चुनें",
      "survey_no": "सर्वे नंबर",
      "search_survey_no_hint":
          "सर्वे नंबर, अक्षांश, देशांतर, क्षेत्रफल से खोजें",
      "add_file": "फ़ाइल जोड़ें",
      "file": "फ़ाइल",
      "upload_consent_forn": "सहमति पत्र अपलोड करें",
    },
    'mr': {
      // General
      'survey_Stats': 'सर्वेक्षण आकडेवारी',
      'survey_overview': 'सर्वेक्षण अवलोकन',
      'pending_survey': 'प्रलंबित सर्वेक्षण',
      'total_surveys': 'एकूण सर्वेक्षण',
      'view_all': 'सर्व पहा',
      'completed': 'पूर्ण झाले',
      'approved_land': 'मंजूर झालेली जमीन',
      'pending': 'प्रलंबित',
      'consent_forms': 'संमती फॉर्म',
      'survey_id': 'सर्वेक्षण आयडी',
      'land_village_district': 'गाव, जिल्हा',
      'land_area': 'जमिनीचे क्षेत्रफळ (एकर मध्ये)',
      'substation_name': 'सबस्टेशनचे नाव',
      'land_type': 'जमिनीचा प्रकार',
      'commercial': 'व्यावसायिक',
      'capacity': 'क्षमता',
      'upload_consent': 'संमती अपलोड करा',
      'edit': 'संपादित करा',
      'delete': 'काढून टाका',
      'survey': 'सर्वेक्षण',
      'home': 'मुख्यपृष्ठ',
      'consent': 'संमती',
      'dashboard': 'डॅशबोर्ड',
      'survey_listing': 'सर्वेक्षण यादी',
      'search': 'शोधा',
      'consent_listing': 'संमती यादी',
      'approved_survey': 'मंजूर झालेली सर्वेक्षण',
      'rejected_survey': 'रद्द केलेले सर्वेक्षण',
      'confirm_location': 'स्थान निश्चित करा',
      'select_location_method': 'आपले स्थान कसे निवडाल?',
      "select_substaion_location_method":
          "आपण आपल्या सबस्टेशनचे स्थान कसे निवडू इच्छिता?",
      'add_manually': 'हस्तनिर्मित जोडा',
      'select_location': 'स्थान निवडा',
      'land_details': 'जमिनीची माहिती',
      'add_survey': 'सर्वेक्षण जोडा',

      // Land & Substation Details
      'sub_basic_detail': 'जमिनीची माहिती',
      'other_detail': 'इतर माहिती',
      'substation_detail': 'सबस्टेशनची माहिती',
      'solar_park_ac_capacity':
          'सौर उर्जा प्रकल्प AC क्षमता (MW)/ DC क्षमता (MWp)',
      'solar_park_ac_capacity_hint': 'सौर उर्जा प्रकल्पाची AC क्षमता भरा',
      'grid_connectivity': 'इंटर कनेक्शनसाठी ग्रिड कनेक्टिव्हिटी S/S',
      'grid_connectivity_hint': 'ग्रिड कनेक्टिव्हिटी भरा',
      'land_state': 'जमिनीचे स्थान, DHQ, राज्य',
      'land_state_hint': 'जमिनीचे स्थान, DHQ, राज्य भरा',
      'land_district': 'जिल्हा',
      'land_district_hint': 'जिल्हा भरा',
      'land_taluka': 'तालुका',
      'land_taluka_hint': 'तालुका भरा',
      'land_village': 'गाव',
      'land_village_hint': 'गाव भरा',
      'land_lat': 'अक्षांश',
      'land_lat_hint': 'अक्षांश भरा',
      'land_long': 'रेखांश',
      'land_long_hint': 'रेखांश भरा',
      'land_area_val': 'जमिनीचे क्षेत्रफळ',
      'land_area_hint': 'जमिनीचे क्षेत्रफळ भरा',
      'land_type_val': 'जमिनीचा प्रकार',
      'land_type_hint': 'जमिनीचा प्रकार निवडा',
      'land_rate': 'जमिनीचा दर/व्यावसायिक/वाढ',
      'land_rate_hint': 'जमिनीचा दर भरा',
      'substation_name_val': 'सबस्टेशनचे नाव',
      'substation_name_hint': 'सबस्टेशनचे नाव भरा',
      'substation_district': 'सबस्टेशन जिल्हा',
      'substation_district_hint': 'सबस्टेशन जिल्हा निवडा',

      'substation_taluka': 'सबस्टेशन तालुका',
      'substation_taluka_hint': 'सबस्टेशनचे तालुका निवडा',

      'substation_village': 'सबस्टेशन गाव',
      'substation_village_hint': 'सबस्टेशनचे गाव निवडा',

      'substation_lat': 'सबस्टेशन अक्षांश',
      'substation_lat_hint': 'सबस्टेशन अक्षांश भरा',
      'substation_long': 'सबस्टेशन रेखांश',
      'substation_long_hint': 'सबस्टेशन रेखांश भरा',
      'substation_incharge_name': 'सबस्टेशन इंचार्ज नाव',
      'substation_incharge_name_hint': 'सबस्टेशन इंचार्ज नाव भरा',
      'substation_incharge_contact': 'सबस्टेशन इंचार्ज संपर्क',
      'substation_incharge_contact_hint': 'सबस्टेशन इंचार्ज संपर्क भरा',
      'operator_name': 'ऑपरेटर नाव',
      'operator_name_hint': 'ऑपरेटर नाव भरा',
      'operator_contact': 'ऑपरेटर संपर्क',
      'operator_contact_hint': 'ऑपरेटर संपर्क भरा',
      'substation_voltage_level': 'सबस्टेशन व्होल्टेज स्तर',
      'substation_voltage_level_hint': 'सबस्टेशन व्होल्टेज स्तर भरा',
      'substation_capacity': 'सबस्टेशन क्षमता',
      'substation_capacity_hint': 'सबस्टेशन क्षमता भरा',
      'distance': 'सबस्टेशन ते जमीन अंतर',
      'distance_hint': 'सबस्टेशन ते जमीन अंतर भरा',
      'plot_distance': 'मुख्य रस्त्यापासून प्लॉट अंतर',
      'plot_distance_hint': 'मुख्य रस्त्यापासून प्लॉट अंतर भरा',
      'evacuation': 'एवॅक्युएशन स्तर',
      'evacuation_hint': 'एवॅक्युएशन स्तर भरा',
      'type_of_soil': 'मातीचा प्रकार / जमिनीचा प्रोफाइल',
      'type_of_soil_hint': 'मातीचा प्रकार भरा',
      'wind_zone': 'वाऱ्याचा झोन',
      'wind_zone_hint': 'वाऱ्याचा झोन भरा',
      'ground_water_rainfall_type': 'भूजल / पर्जन्य प्रमाण',
      'nearest_highway': 'जवळची महामार्ग',
      'nearest_highway_hint': 'जवळची महामार्ग भरा',
      'land_form_image': 'जमिनीचा फॉर्म प्रतिमा',
      'land_images': 'जमिनीच्या प्रतिमा',
      'save_exit': 'साठवून बाहेर पडा',
      'previous': 'मागील',
      'submit': 'सादर करा',
      'continue': 'सुरू ठेवा',
      'are_you_sure_logout': 'तुम्ही खरंच लॉगआउट करू इच्छिता?',
      'cancel': 'रद्द करा',
      'logout': 'लॉगआउट',
      'rejected': 'रद्द',
      'approved': 'मंजूर',
      'add_consent': 'संमती जोडा',
      'select_district': 'जिल्हा निवडा',
      'select_taluka': 'तालुका निवडा',
      'select_village': 'गाव निवडा',
      'syncNow': 'आता सिंक करा',

      
      "add_land_Survey": "भू सर्वे जोडणे",
      "select_survey_no": "सर्वे क्रमांक निवडा",
      "survey_no": "सर्वे क्रमांक",
      "search_survey_no_hint":
          "सर्वे क्रमांक, अक्षांश, रेखांश, क्षेत्रफळानुसार शोधा",
      "add_file": "फाईल जोडा",
      "file": "फाईल",
      "upload_consent_forn": "सहमती फॉर्म अपलोड करा",
    }
  };
}
